---
Name: mytheme
---
SilverStripe\View\SSViewer:
  themes:
    - 'thehustlers'
    - '$public'
    - 'simple'
    - '$default'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - GlobalSettingsExtension